### ISSUE TITLE
NavSec1 - Navigation Section 1

### ISSUE THREAD

**Issue by bannerintheUK** [pro-fas/lagergeld#13]
## First Navigation Section
![navsec1 1](https://user-images.githubusercontent.com/5251018/29180034-b646e51a-7df6-11e7-87cf-66a70a022b69.png)

### Composes
- [x] **InfoTxt** - Information text #14 
- [x] **Col1** - Column 1 (Infographic ) #15
- [x] **Col2** - Column 2 (Video) #16
- [x] **Col3** - Column 3 (Timeline) #17

- [x] **Completed**

**Comment by bannerintheUK** [comment]
Done
