### ISSUE TITLE
LaPa01 - Landing Page Draft 1

### ISSUE THREAD

**Issue by bannerintheUK** [pro-fas/lagergeld#3]
#### Initial entry point to Lager Sylt Application

![landing page](https://user-images.githubusercontent.com/5251018/29138544-52ead86c-7d44-11e7-9801-13b5841660ef.png)

## composes
- [x]  **HeSec1** - Header Section 1 #4 
   
- [x]  **NavSec1** - Navigation Section 1 #13
   
- [x]  **NavSec2** - Navigation Section 2 #18 
   
- [x]  **RefSec** - References Section #21 
  
- [x]  **Foo1** - Footer #22

**Comment by HTitcomb-Day** [comment]
# Navigation Section 1

![navsec1](https://user-images.githubusercontent.com/30464879/29180983-6eed4150-7df1-11e7-9174-cad74f37fdbf.png)

# Composes
+ Wra02 - Wrapper 2 
+ BanTxt2 - Banner Text 2
+ InBtn - Infographic Button
+ ViBtn - Video Button
+ TiBtn - Timeline Button 
+ Box01
+ Box02
+ Box03
+ Ico01 - 'I' Icon
+ Ico02 - Triangle Icon
+ Ico03 - Clock Icon

**Comment by HTitcomb-Day** [comment]
# Navigation Section 2

![navsec2](https://user-images.githubusercontent.com/30464879/29184346-c4425206-7dfd-11e7-9911-7471a9a92cc9.png)

# Composes

+ ViToBtn - Virtual Tour Button
+ 3dReBtn - 3D Reconstruction Button 
+ Box04
+ Box05

**Comment by HTitcomb-Day** [comment]
# References Section

![refsec](https://user-images.githubusercontent.com/30464879/29184706-fe2d7936-7dfe-11e7-9f4f-1684e6e499c0.png)

# Composes
+ RefBtn

**Comment by bannerintheUK** [comment]
Done
